import { Link, useNavigate } from '@tanstack/react-router';
import { useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { useSkyarth, type Collection, type ContentKey } from '@/lib/skyarth-context';
import { photo, type Entity, type Property } from '@/lib/skyarth-data';
import { Arrow, Brand, Button, Icon, Photo } from './ui';

const adminItems=[['Dashboard','dashboard','chart'],['Properties','properties','building'],['Property Categories','categories','home'],['Projects','projects','building'],['Services','services','key'],['Testimonials','testimonials','star'],['Enquiries','enquiries','mail'],['Hero Banner','hero','edit'],['About Content','about','edit'],['Why SKYARTH','why','shield'],['Contact Information','contact','phone'],['Website Settings','settings','edit']] as const;
type AdminSection=typeof adminItems[number][1];
const text=(value:unknown)=>String(value??'');
const list=(value:unknown)=>Array.isArray(value)?value.join(', '):text(value);
const bool=(value:unknown)=>Boolean(value);

export function AdminLoginPage(){const {loggedIn,setLoggedIn}=useSkyarth();const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');if(loggedIn){void navigate({to:'/admin/dashboard',replace:true});return null;}const submit=(event:FormEvent)=>{event.preventDefault();if(email==='admin@skyarthproperty.com'&&password==='admin123'){setLoggedIn(true);void navigate({to:'/admin/dashboard',replace:true});}else setError('Email or password does not match the demo credentials.');};return <main className="admin-login"><section className="login-visual"><Photo src={photo(47)} alt="Premium architectural residence for SKYARTH administration" eager/><div className="image-shade"/><Brand/><div className="login-visual-content"><p className="eyebrow">SKYARTH ADMINISTRATION</p><h1>Manage every property opportunity from one place.</h1><p>Frontend demonstration panel. Changes remain available during this browser session only.</p></div></section><section className="login-form-area"><form className="login-form" onSubmit={submit}><p className="eyebrow">ADMIN ACCESS</p><h2>Welcome back.</h2><p>Sign in to manage the SKYARTH Property website.</p><label className="field"><span>Email address</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="username"/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<p className="field-error" role="alert">{error}</p>}<Button type="submit" variant="navy">Sign In <Arrow diagonal/></Button><div className="login-demo"><strong>Demo credentials</strong><span>admin@skyarthproperty.com</span><br/><span>admin123</span></div><Link to="/" className="back-site">← Back to public website</Link></form></section></main>}

export function AdminDashboardPage(){const store=useSkyarth();const navigate=useNavigate();const [section,setSection]=useState<AdminSection>('dashboard');const [menu,setMenu]=useState(false);if(!store.loggedIn){void navigate({to:'/admin/login',replace:true});return null;}const current=adminItems.find(x=>x[1]===section);const logout=()=>{store.setLoggedIn(false);void navigate({to:'/admin/login',replace:true});};return <div className="admin-shell"><aside className={`admin-sidebar ${menu?'open':''}`}><Brand/><nav aria-label="Admin navigation">{adminItems.map(([label,key,icon])=><button className={`admin-nav-button ${section===key?'active':''}`} key={key} onClick={()=>{setSection(key);setMenu(false)}}><Icon name={icon}/>{label}</button>)}</nav><div className="logout"><button className="admin-nav-button" onClick={logout}><Icon name="logout"/>Logout</button></div></aside><main className="admin-main"><header className="admin-header"><Button variant="ghost" className="admin-mobile-menu" aria-label="Open admin menu" onClick={()=>setMenu(!menu)}><Icon name={menu?'close':'menu'}/></Button><div><h1>{current?.[0]}</h1><p>Frontend demo · Changes apply to the public website for this session</p></div><Link to="/" className="button button-outline">View Website <Arrow diagonal/></Link></header><div className="admin-content"><AdminSectionView section={section}/></div></main></div>}

function AdminSectionView({section}:{section:AdminSection}){if(section==='dashboard')return <Dashboard/>;if(section==='properties')return <PropertyManager/>;if(section==='categories')return <SimpleManager collection="categories" title="Property Categories" fields={['name','description','image']}/>;if(section==='projects')return <SimpleManager collection="projects" title="Projects" fields={['name','location','category','description','image','secondaryImage','status','galleryImages','featured']}/>;if(section==='services')return <SimpleManager collection="services" title="Services" fields={['name','description','image','process','cta','enabled']}/>;if(section==='testimonials')return <SimpleManager collection="testimonials" title="Testimonials" fields={['name','location','type','quote','rating','published']}/>;if(section==='enquiries')return <EnquiryManager/>;if(section==='hero')return <ContentEditor contentKey="hero" title="Hero Banner" fields={['heading','subtitle','image','primaryCTA','secondaryCTA']}/>;if(section==='about')return <ContentEditor contentKey="about" title="About Content" fields={['heading','description','image','supportingImage','mission','vision','values']}/>;if(section==='why')return <ContentEditor contentKey="why" title="Why SKYARTH" fields={['heading','description','image','philosophy','reasons']}/>;if(section==='contact')return <ContentEditor contentKey="settings" title="Contact Information" fields={['name','phone','email']}/>;return <ContentEditor contentKey="settings" title="Website Settings" fields={['name','phone','email','footerText','primaryCTA','secondaryCTA','socialLinkedIn','socialInstagram','socialFacebook','websiteStatus']}/>}

function Dashboard(){const s=useSkyarth();const stats=[['Total Properties',s.properties.length,'building'],['Featured Properties',s.properties.filter(x=>x.featured).length,'star'],['Total Projects',s.projects.length,'home'],['Total Enquiries',s.enquiries.length,'mail'],['Active Services',s.services.filter(x=>x.enabled).length,'key'],['Testimonials',s.testimonials.filter(x=>x.published).length,'star']];const categoryCounts=['Residential','Commercial','Investment','Land'].map(name=>({name,count:s.properties.filter(x=>x.category===name).length}));return <><div className="admin-stats">{stats.map(([label,value,icon])=><article className="admin-stat" key={label}><div><p>{label}</p><strong>{value}</strong></div><Icon name={String(icon)}/></article>)}</div><div className="admin-grid"><section className="admin-panel"><h2>Property Portfolio</h2><div className="chart-bars">{categoryCounts.map(x=><div key={x.name}><strong>{x.count}</strong><div className="chart-bar" style={{height:`${Math.max(18,x.count*34)}px`}}/><span>{x.name}</span></div>)}</div></section><section className="admin-panel"><h2>Recent Enquiries</h2>{s.enquiries.slice(-5).reverse().map(x=><div className="admin-recent" key={x.id}><div><strong>{x.name}</strong><p>{text(x.property||x.requirement)}</p></div><span className="badge">{text(x.status)}</span></div>)}</section></div></>}

const propertyFields=['name','location','neighborhood','category','type','price','area','bedrooms','bathrooms','status','description','image','thumbnail','exteriorImage','interiorImages','galleryImages','amenities','features','advantages','featured'];
function PropertyManager(){const {properties,save,remove}=useSkyarth();const [editing,setEditing]=useState<Entity|null>(null);return <ManagerShell title="Properties" count={properties.length} onAdd={()=>setEditing(newProperty())}><div className="table-wrap"><table><thead><tr><th>Property</th><th>Location</th><th>Type</th><th>Price</th><th>Status</th><th>Featured</th><th>Actions</th></tr></thead><tbody>{properties.map(p=><tr key={p.id}><td><div className="table-property"><Photo src={p.image} alt=""/><strong>{p.name}</strong></div></td><td>{p.location}</td><td>{p.type}</td><td>₹{p.price} Lakh</td><td>{p.status}</td><td><input className="switch" type="checkbox" checked={p.featured} onChange={()=>save('properties',{...p,featured:!p.featured})}/></td><td><Actions onEdit={()=>setEditing(p)} onDelete={()=>confirm(`Delete ${p.name}?`)&&remove('properties',p.id)}/></td></tr>)}</tbody></table></div>{editing&&<EntityModal title={editing.id.startsWith('new-')?'Add Property':'Edit Property'} item={editing} fields={propertyFields} onClose={()=>setEditing(null)} onSave={item=>{save('properties',normalizeProperty(item));setEditing(null)}}/>}</ManagerShell>}

function SimpleManager({collection,title,fields}:{collection:Exclude<Collection,'properties'|'enquiries'>;title:string;fields:string[]}){const store=useSkyarth();const items=store[collection] as Entity[];const [editing,setEditing]=useState<Entity|null>(null);return <ManagerShell title={title} count={items.length} onAdd={()=>setEditing({id:`new-${Date.now()}`,name:'',image:photo(items.length+6)})}><div className="table-wrap"><table><thead><tr><th>Name</th><th>Details</th>{fields.some(isBooleanField)&&<th>Active</th>}<th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong></td><td className="table-copy">{text(item.description||item.quote||item.location)}</td>{fields.some(isBooleanField)&&<td>{fields.filter(isBooleanField).map(key=><label className="admin-inline-label" key={key}><input className="switch" type="checkbox" checked={bool(item[key])} onChange={()=>store.save(collection,{...item,[key]:!item[key]})}/>{human(key)}</label>)}</td>}<td><Actions onEdit={()=>setEditing(item)} onDelete={()=>confirm(`Delete ${item.name}?`)&&store.remove(collection,item.id)}/></td></tr>)}</tbody></table></div>{editing&&<EntityModal title={editing.id.startsWith('new-')?`Add ${title.replace(/s$/,'')}`:`Edit ${editing.name}`} item={editing} fields={fields} onClose={()=>setEditing(null)} onSave={item=>{store.save(collection,item);setEditing(null)}}/>}</ManagerShell>}

function EnquiryManager(){const {enquiries,save,remove}=useSkyarth();const [status,setStatus]=useState('All');const shown=useMemo(()=>status==='All'?enquiries:enquiries.filter(x=>x.status===status),[enquiries,status]);return <ManagerShell title="Enquiries" count={shown.length}><div className="admin-enquiry-filters"><label className="field"><span>Filter by status</span><select value={status} onChange={e=>setStatus(e.target.value)}>{['All','New','Contacted','Follow-up','Closed'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Interested Property</th><th>Requirement</th><th>Date</th><th>Status</th><th>Action</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td>{x.name}</td><td>{text(x.phone)}<br/>{text(x.email)}</td><td>{text(x.property||x.interestedIn)}</td><td className="table-copy">{text(x.requirement||x.message)}</td><td>{text(x.date)}</td><td><select className="status-select" value={text(x.status)} onChange={e=>save('enquiries',{...x,status:e.target.value})}>{['New','Contacted','Follow-up','Closed'].map(v=><option key={v}>{v}</option>)}</select></td><td><Button variant="ghost" aria-label={`Delete ${x.name}`} onClick={()=>confirm(`Delete enquiry from ${x.name}?`)&&remove('enquiries',x.id)}><Icon name="trash"/></Button></td></tr>)}</tbody></table></div></ManagerShell>}

function ContentEditor({contentKey,title,fields}:{contentKey:ContentKey;title:string;fields:string[]}){const store=useSkyarth();const source=store[contentKey];const [draft,setDraft]=useState<Entity>({...source});const [saved,setSaved]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();store.updateContent(contentKey,draft);setSaved(true);setTimeout(()=>setSaved(false),2200)};return <form className="admin-content-form" onSubmit={submit}><h2>{title}</h2><div className="form-grid">{fields.map(key=><EditorField key={key} field={key} value={draft[key]} onChange={value=>setDraft({...draft,[key]:value})}/>)}</div><Button type="submit" variant="navy">Save Changes</Button>{saved&&<p className="saved-message" role="status">Changes saved and reflected on the public website.</p>}</form>}

function ManagerShell({title,count,onAdd,children}:{title:string;count:number;onAdd?:()=>void;children:ReactNode}){return <section><div className="admin-toolbar"><div><h2>{title}</h2><p>{count} current records</p></div>{onAdd&&<Button variant="navy" onClick={onAdd}><Icon name="plus"/>Add New</Button>}</div>{children}</section>}
function Actions({onEdit,onDelete}:{onEdit:()=>void;onDelete:()=>void}){return <div className="row-actions"><Button variant="ghost" aria-label="Edit" onClick={onEdit}><Icon name="edit"/></Button><Button variant="ghost" aria-label="Delete" onClick={onDelete}><Icon name="trash"/></Button></div>}
function EntityModal({title,item,fields,onClose,onSave}:{title:string;item:Entity;fields:string[];onClose:()=>void;onSave:(item:Entity)=>void}){const [draft,setDraft]=useState({...item});const submit=(e:FormEvent)=>{e.preventDefault();if(!text(draft.name).trim())return;onSave({...draft,id:draft.id.startsWith('new-')?`${text(draft.name).toLowerCase().replace(/[^a-z0-9]+/g,'-')}-${Date.now()}`:draft.id})};return <div className="modal-backdrop" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal edit-modal" role="dialog" aria-modal="true" aria-label={title} onSubmit={submit}><Button variant="ghost" className="modal-close" aria-label="Close" onClick={onClose}><Icon name="close"/></Button><h2>{title}</h2><div className="form-grid">{fields.map(key=><EditorField key={key} field={key} value={draft[key]} onChange={value=>setDraft({...draft,[key]:value})}/>)}</div><div className="modal-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit" variant="navy">Save</Button></div></form></div>}
function EditorField({field,value,onChange}:{field:string;value:unknown;onChange:(value:string|number|boolean|string[])=>void}){if(isBooleanField(field))return <label className="admin-inline-label full"><input className="switch" type="checkbox" checked={bool(value)} onChange={e=>onChange(e.target.checked)}/>{human(field)}</label>;const isList=['galleryImages','interiorImages','amenities','features','advantages','highlights','process','values','reasons'].includes(field);const isLong=['description','quote','subtitle','mission','vision','philosophy','footerText'].includes(field);const numeric=['price','area','bedrooms','bathrooms','rating'].includes(field);const select:Record<string,string[]>={category:['Residential','Commercial','Investment','Land'],status:['Ready to Move','Under Construction','New','Contacted','Follow-up','Closed'],websiteStatus:['Live','Maintenance']};return <label className={`field ${isLong||isList?'full':''}`}><span>{human(field)}{isList?' (comma separated)':''}</span>{select[field]?<select value={text(value)} onChange={e=>onChange(e.target.value)}>{select[field].map(x=><option key={x}>{x}</option>)}</select>:isLong||isList?<textarea value={list(value)} onChange={e=>onChange(isList?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value)}/>:<input type={numeric?'number':field.toLowerCase().includes('email')?'email':field.toLowerCase().includes('image')||field.startsWith('social')?'url':'text'} value={text(value)} onChange={e=>onChange(numeric?Number(e.target.value):e.target.value)} required={field==='name'}/>} {field.toLowerCase().includes('image')&&text(value)&&<Photo className="image-preview" src={text(value)} alt={`${human(field)} preview`}/>}</label>}
function isBooleanField(field:string){return ['featured','enabled','published'].includes(field)}
function human(field:string){return field.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase())}
function newProperty():Property{return {id:`new-${Date.now()}`,name:'',location:'Pune',neighborhood:'',category:'Residential',type:'3 BHK Apartment',price:100,area:1200,bedrooms:3,bathrooms:2,status:'Ready to Move',featured:false,image:photo(0),galleryImages:[photo(0)],description:'',amenities:[],features:[],advantages:[]}}
function normalizeProperty(item:Entity):Property{return {...newProperty(),...item,price:Number(item.price)||0,area:Number(item.area)||0,bedrooms:Number(item.bedrooms)||0,bathrooms:Number(item.bathrooms)||0,featured:Boolean(item.featured),galleryImages:Array.isArray(item.galleryImages)?item.galleryImages:[],amenities:Array.isArray(item.amenities)?item.amenities:[],features:Array.isArray(item.features)?item.features:[],advantages:Array.isArray(item.advantages)?item.advantages:[]} as Property}
